#!/bin/sh
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

PATTERN="^cds-[0-9]+ (feat|fix|chore|docs|style|refactor|perf|test): .+"

if ! echo "$COMMIT_MSG" | grep -E "$PATTERN"; then
  echo "Erro: A mensagem de commit deve seguir o padrão 'cds-{número da task} {tipo de commit}: {descrição}'"
  exit 1
fi
